current colors:
- '#002451'
- '#001C40'
- '#008000'
- '#ffffff'
- '#bf7900'
- '#d40000'
custom palette 1: []
custom palette 2: []
custom palette 3:
- '#3f3f3f'
- '#808080'
- '#008000'
- '#ffffff'
- '#bf7900'
- '#d40000'
